/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrabajaConNosotrosRouteImport } from './routes/trabaja-con-nosotros'
import { Route as SobreNosotrosRouteImport } from './routes/sobre-nosotros'
import { Route as ServiciosRouteImport } from './routes/servicios'
import { Route as ProyectosRouteImport } from './routes/proyectos'
import { Route as ContactoRouteImport } from './routes/contacto'
import { Route as CanalDelInformanteRouteImport } from './routes/canal-del-informante'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EmpleoIdRouteImport } from './routes/empleo.$id'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminEmpleoRouteImport } from './routes/admin.empleo'

const TrabajaConNosotrosRoute = TrabajaConNosotrosRouteImport.update({
  id: '/trabaja-con-nosotros',
  path: '/trabaja-con-nosotros',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreNosotrosRoute = SobreNosotrosRouteImport.update({
  id: '/sobre-nosotros',
  path: '/sobre-nosotros',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiciosRoute = ServiciosRouteImport.update({
  id: '/servicios',
  path: '/servicios',
  getParentRoute: () => rootRouteImport,
} as any)
const ProyectosRoute = ProyectosRouteImport.update({
  id: '/proyectos',
  path: '/proyectos',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactoRoute = ContactoRouteImport.update({
  id: '/contacto',
  path: '/contacto',
  getParentRoute: () => rootRouteImport,
} as any)
const CanalDelInformanteRoute = CanalDelInformanteRouteImport.update({
  id: '/canal-del-informante',
  path: '/canal-del-informante',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EmpleoIdRoute = EmpleoIdRouteImport.update({
  id: '/empleo/$id',
  path: '/empleo/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminEmpleoRoute = AdminEmpleoRouteImport.update({
  id: '/admin/empleo',
  path: '/admin/empleo',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/canal-del-informante': typeof CanalDelInformanteRoute
  '/contacto': typeof ContactoRoute
  '/proyectos': typeof ProyectosRoute
  '/servicios': typeof ServiciosRoute
  '/sobre-nosotros': typeof SobreNosotrosRoute
  '/trabaja-con-nosotros': typeof TrabajaConNosotrosRoute
  '/admin/empleo': typeof AdminEmpleoRoute
  '/admin/login': typeof AdminLoginRoute
  '/empleo/$id': typeof EmpleoIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/canal-del-informante': typeof CanalDelInformanteRoute
  '/contacto': typeof ContactoRoute
  '/proyectos': typeof ProyectosRoute
  '/servicios': typeof ServiciosRoute
  '/sobre-nosotros': typeof SobreNosotrosRoute
  '/trabaja-con-nosotros': typeof TrabajaConNosotrosRoute
  '/admin/empleo': typeof AdminEmpleoRoute
  '/admin/login': typeof AdminLoginRoute
  '/empleo/$id': typeof EmpleoIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/canal-del-informante': typeof CanalDelInformanteRoute
  '/contacto': typeof ContactoRoute
  '/proyectos': typeof ProyectosRoute
  '/servicios': typeof ServiciosRoute
  '/sobre-nosotros': typeof SobreNosotrosRoute
  '/trabaja-con-nosotros': typeof TrabajaConNosotrosRoute
  '/admin/empleo': typeof AdminEmpleoRoute
  '/admin/login': typeof AdminLoginRoute
  '/empleo/$id': typeof EmpleoIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/canal-del-informante'
    | '/contacto'
    | '/proyectos'
    | '/servicios'
    | '/sobre-nosotros'
    | '/trabaja-con-nosotros'
    | '/admin/empleo'
    | '/admin/login'
    | '/empleo/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/canal-del-informante'
    | '/contacto'
    | '/proyectos'
    | '/servicios'
    | '/sobre-nosotros'
    | '/trabaja-con-nosotros'
    | '/admin/empleo'
    | '/admin/login'
    | '/empleo/$id'
  id:
    | '__root__'
    | '/'
    | '/canal-del-informante'
    | '/contacto'
    | '/proyectos'
    | '/servicios'
    | '/sobre-nosotros'
    | '/trabaja-con-nosotros'
    | '/admin/empleo'
    | '/admin/login'
    | '/empleo/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CanalDelInformanteRoute: typeof CanalDelInformanteRoute
  ContactoRoute: typeof ContactoRoute
  ProyectosRoute: typeof ProyectosRoute
  ServiciosRoute: typeof ServiciosRoute
  SobreNosotrosRoute: typeof SobreNosotrosRoute
  TrabajaConNosotrosRoute: typeof TrabajaConNosotrosRoute
  AdminEmpleoRoute: typeof AdminEmpleoRoute
  AdminLoginRoute: typeof AdminLoginRoute
  EmpleoIdRoute: typeof EmpleoIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trabaja-con-nosotros': {
      id: '/trabaja-con-nosotros'
      path: '/trabaja-con-nosotros'
      fullPath: '/trabaja-con-nosotros'
      preLoaderRoute: typeof TrabajaConNosotrosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre-nosotros': {
      id: '/sobre-nosotros'
      path: '/sobre-nosotros'
      fullPath: '/sobre-nosotros'
      preLoaderRoute: typeof SobreNosotrosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicios': {
      id: '/servicios'
      path: '/servicios'
      fullPath: '/servicios'
      preLoaderRoute: typeof ServiciosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proyectos': {
      id: '/proyectos'
      path: '/proyectos'
      fullPath: '/proyectos'
      preLoaderRoute: typeof ProyectosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacto': {
      id: '/contacto'
      path: '/contacto'
      fullPath: '/contacto'
      preLoaderRoute: typeof ContactoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/canal-del-informante': {
      id: '/canal-del-informante'
      path: '/canal-del-informante'
      fullPath: '/canal-del-informante'
      preLoaderRoute: typeof CanalDelInformanteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/empleo/$id': {
      id: '/empleo/$id'
      path: '/empleo/$id'
      fullPath: '/empleo/$id'
      preLoaderRoute: typeof EmpleoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/empleo': {
      id: '/admin/empleo'
      path: '/admin/empleo'
      fullPath: '/admin/empleo'
      preLoaderRoute: typeof AdminEmpleoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CanalDelInformanteRoute: CanalDelInformanteRoute,
  ContactoRoute: ContactoRoute,
  ProyectosRoute: ProyectosRoute,
  ServiciosRoute: ServiciosRoute,
  SobreNosotrosRoute: SobreNosotrosRoute,
  TrabajaConNosotrosRoute: TrabajaConNosotrosRoute,
  AdminEmpleoRoute: AdminEmpleoRoute,
  AdminLoginRoute: AdminLoginRoute,
  EmpleoIdRoute: EmpleoIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
